# -*- coding: utf-8 -*-
"""Copy of Green amd Ampt Infiltration Law.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXLaAhtG9K-nYWGc-qYrY3MJLdILroXl

**Green-Ampt Infiltration Model**

Infiltration rate:
$$f(t) = K_s \left(1 + \frac{\psi \cdot \Delta\Theta}{F(t)}\right)$$

Cumulative infiltration (implicit):
$$F(t) = K_s t + \psi \cdot \Delta\Theta \ln\left(1 + \frac{F(t)}{\psi \cdot \Delta\Theta}\right)$$

where $\Delta\Theta = \theta_s - \theta_i$
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install ipywidgets --quiet

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from ipywidgets import interact, FloatSlider, Dropdown, Output
import ipywidgets as widgets
from IPython.display import display, clear_output

# ── Soil presets (Rawls et al.) ──────────────────────────────
PRESETS = {
    "Sand":       dict(Ks=117.8, psi=49.5,  ths=0.437, thi=0.020),
    "Loamy sand": dict(Ks=29.9,  psi=61.3,  ths=0.437, thi=0.036),
    "Sandy loam": dict(Ks=10.9,  psi=110.1, ths=0.453, thi=0.041),
    "Loam":       dict(Ks=3.4,   psi=88.9,  ths=0.463, thi=0.052),
    "Silt loam":  dict(Ks=6.5,   psi=166.8, ths=0.501, thi=0.030),
    "Clay loam":  dict(Ks=1.0,   psi=208.8, ths=0.464, thi=0.063),
    "Clay":       dict(Ks=0.3,   psi=316.3, ths=0.475, thi=0.068),
}

# ── Green-Ampt solver ────────────────────────────────────────
def solve_green_ampt(Ks, psi, dtheta, duration_hr, N=300):
    """
    Solves F(t) implicitly via Newton iteration, then derives f(t).

    Governing equation:
        F(t) = Ks*t + psi*dtheta * ln(1 + F(t)/(psi*dtheta))

    Infiltration rate:
        f(t) = Ks * (1 + psi*dtheta / F(t))
    """
    dt = duration_hr / N
    times = np.linspace(0, duration_hr, N + 1)
    F = np.zeros(N + 1)
    f = np.zeros(N + 1)

    f[0] = Ks * (1 + psi * dtheta / 1e-9)   # near-infinite at t=0

    for i in range(1, N + 1):
        F_prev = F[i - 1]
        # Newton-Raphson to solve implicit equation
        F_new = F_prev + Ks * dt              # initial guess
        for _ in range(50):
            lhs = F_new
            rhs = (F_prev + Ks * dt +
                   psi * dtheta * np.log((F_new + psi * dtheta) /
                                         (F_prev + psi * dtheta)))
            F_new = rhs
            if abs(F_new - lhs) < 1e-8:
                break
        F[i] = F_new
        f[i] = Ks * (1 + psi * dtheta / F_new)

    return times, F, f


# ── Plot function ────────────────────────────────────────────
def run_simulation(preset, Ks, psi, ths, thi, rainfall, duration):
    dtheta = max(0.001, ths - thi)
    times, F, f = solve_green_ampt(Ks, psi, dtheta, duration)

    # Cap infiltration rate at rainfall intensity (ponding)
    f_actual = np.minimum(f, rainfall)
    rain_cum  = rainfall * times
    runoff    = np.maximum(0, rain_cum - F)

    # Find ponding time
    ponding_time = None
    for i, fi in enumerate(f):
        if fi <= rainfall:
            ponding_time = times[i]
            break

    # ── Metrics ──
    total_inf    = F[-1]
    total_rain   = rainfall * duration
    total_runoff = max(0, total_rain - total_inf)
    final_rate   = f_actual[-1]

    # ── Figure ──────────────────────────────────────────────
    fig = plt.figure(figsize=(14, 9))
    fig.patch.set_facecolor('#f8f9fa')
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

    BLUE   = '#378ADD'
    GREEN  = '#1D9E75'
    ORANGE = '#D85A30'
    GRAY   = '#888780'

    # ── Panel 1: Infiltration rate ───────────────────────────
    ax1 = fig.add_subplot(gs[0, :2])
    ax1.fill_between(times, f_actual, alpha=0.15, color=GREEN)
    ax1.plot(times, f_actual, color=GREEN, lw=2, label='Infiltration rate f(t)')
    ax1.axhline(rainfall, color=BLUE, lw=1.5, ls='--', label=f'Rainfall intensity i = {rainfall:.0f} mm/hr')
    if ponding_time:
        ax1.axvline(ponding_time, color=ORANGE, lw=1.2, ls=':', alpha=0.8,
                    label=f'Ponding at t = {ponding_time:.2f} hr')
    ax1.set_xlabel('Time (hr)', color=GRAY, fontsize=10)
    ax1.set_ylabel('mm / hr', color=GRAY, fontsize=10)
    ax1.set_title('Infiltration rate', fontsize=12, fontweight='normal', color='#2C2C2A')
    ax1.legend(fontsize=9, framealpha=0.5)
    ax1.set_facecolor('#ffffff')
    ax1.tick_params(colors=GRAY)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)

    # ── Panel 2: Soil texture schematic ─────────────────────
    ax2 = fig.add_subplot(gs[0, 2])
    ax2.set_facecolor('#ffffff')
    ax2.set_xlim(0, 1); ax2.set_ylim(0, 1)
    ax2.axis('off')
    ax2.set_title('Soil moisture profile', fontsize=12, fontweight='normal', color='#2C2C2A')

    # Draw soil column with moisture gradient
    n_layers = 20
    wf_depth = min(0.9, F[-1] / max(F[-1], 1) * 0.85 + 0.05)
    for j in range(n_layers):
        depth_frac = j / n_layers
        if depth_frac < wf_depth:
            color = plt.cm.Blues(0.3 + 0.5 * (1 - depth_frac / wf_depth))
        else:
            color = plt.cm.YlOrBr(0.2 + 0.3 * thi / max(ths, 0.001))
        rect = plt.Rectangle((0.2, 1 - (j+1)/n_layers), 0.6, 1/n_layers,
                               facecolor=color, edgecolor='#cccccc', lw=0.3)
        ax2.add_patch(rect)

    ax2.annotate('', xy=(0.5, 1 - wf_depth), xytext=(0.5, 1 - wf_depth - 0.08),
                 arrowprops=dict(arrowstyle='->', color=ORANGE, lw=1.5))
    ax2.text(0.5, 1 - wf_depth - 0.13, 'Wetting front', ha='center',
             fontsize=8, color=ORANGE)
    ax2.text(0.5, 1.02, 'Surface', ha='center', fontsize=8, color=GRAY)
    ax2.text(0.15, 0.92, f'θ = θs\n{ths:.3f}', ha='center', fontsize=7.5, color='#0C447C')
    ax2.text(0.15, 0.35, f'θ = θi\n{thi:.3f}', ha='center', fontsize=7.5, color='#5F5E5A')

    # ── Panel 3: Cumulative ──────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    ax3.fill_between(times, F, alpha=0.15, color=GREEN)
    ax3.plot(times, F, color=GREEN, lw=2, label='Cumulative F(t)')
    ax3.plot(times, rain_cum, color=BLUE, lw=1.5, ls='--', label='Cumulative rainfall')
    ax3.fill_between(times, F, rain_cum, where=(rain_cum > F), alpha=0.12,
                     color=ORANGE, label='Runoff zone')
    ax3.set_xlabel('Time (hr)', color=GRAY, fontsize=10)
    ax3.set_ylabel('mm', color=GRAY, fontsize=10)
    ax3.set_title('Cumulative infiltration', fontsize=12, fontweight='normal', color='#2C2C2A')
    ax3.legend(fontsize=8, framealpha=0.5)
    ax3.set_facecolor('#ffffff')
    ax3.tick_params(colors=GRAY)
    ax3.spines['top'].set_visible(False)
    ax3.spines['right'].set_visible(False)

    # ── Panel 4: Runoff ──────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.fill_between(times, runoff, alpha=0.15, color=ORANGE)
    ax4.plot(times, runoff, color=ORANGE, lw=2, label='Cumulative runoff')
    ax4.set_xlabel('Time (hr)', color=GRAY, fontsize=10)
    ax4.set_ylabel('mm', color=GRAY, fontsize=10)
    ax4.set_title('Surface runoff', fontsize=12, fontweight='normal', color='#2C2C2A')
    ax4.legend(fontsize=8, framealpha=0.5)
    ax4.set_facecolor('#ffffff')
    ax4.tick_params(colors=GRAY)
    ax4.spines['top'].set_visible(False)
    ax4.spines['right'].set_visible(False)

    # ── Panel 5: Summary metrics ─────────────────────────────
    ax5 = fig.add_subplot(gs[1, 2])
    ax5.set_facecolor('#ffffff')
    ax5.axis('off')
    ax5.set_title('Summary', fontsize=12, fontweight='normal', color='#2C2C2A')

    metrics = [
        ('Final infil. rate',  f'{final_rate:.2f} mm/hr'),
        ('Total infiltration',  f'{total_inf:.1f} mm'),
        ('Total rainfall',      f'{total_rain:.1f} mm'),
        ('Total runoff',        f'{total_runoff:.1f} mm'),
        ('Runoff ratio',        f'{100*total_runoff/max(total_rain,0.001):.1f} %'),
        ('Ponding time',        f'{ponding_time:.3f} hr' if ponding_time else 'None'),
        ('Ks',                  f'{Ks:.1f} mm/hr'),
        ('ψ (suction)',         f'{psi:.1f} mm'),
        ('ΔΘ (moisture def.)', f'{dtheta:.3f}'),
    ]
    for k, (label, val) in enumerate(metrics):
        y = 0.92 - k * 0.10
        ax5.text(0.05, y, label, fontsize=9, color=GRAY, va='top')
        ax5.text(0.98, y, val,   fontsize=9, color='#2C2C2A', va='top',
                 ha='right', fontweight='normal')
        ax5.axhline(y - 0.025, xmin=0.03, xmax=0.97, color='#e0e0e0', lw=0.5)

    fig.suptitle(f'Green-Ampt infiltration  —  {preset}',
                 fontsize=14, fontweight='normal', color='#2C2C2A', y=1.01)
    plt.tight_layout()
    plt.show()


# ── Widgets ──────────────────────────────────────────────────
style  = {'description_width': '160px'}
layout = widgets.Layout(width='480px')

w_preset   = Dropdown(options=list(PRESETS.keys()), value='Sandy loam',
                       description='Soil type preset:', style=style, layout=layout)
w_Ks       = FloatSlider(min=0.1,  max=120,  step=0.1,  value=10.9,  description='Ks (mm/hr):',       style=style, layout=layout, readout_format='.1f')
w_psi      = FloatSlider(min=10,   max=400,  step=1,    value=110.1, description='ψ suction (mm):',   style=style, layout=layout, readout_format='.1f')
w_ths      = FloatSlider(min=0.30, max=0.60, step=0.001,value=0.453, description='θs porosity:',      style=style, layout=layout, readout_format='.3f')
w_thi      = FloatSlider(min=0.01, max=0.55, step=0.001,value=0.041, description='θi initial moist.:', style=style, layout=layout, readout_format='.3f')
w_rainfall = FloatSlider(min=5,    max=200,  step=1,    value=50,    description='Rainfall (mm/hr):', style=style, layout=layout, readout_format='.0f')
w_duration = FloatSlider(min=0.5,  max=24,   step=0.5,  value=6,     description='Duration (hr):',    style=style, layout=layout, readout_format='.1f')

# Auto-fill sliders when preset changes
def on_preset_change(change):
    p = PRESETS[change['new']]
    w_Ks.value  = p['Ks']
    w_psi.value = p['psi']
    w_ths.value = p['ths']
    w_thi.value = p['thi']

w_preset.observe(on_preset_change, names='value')

out = Output()

def on_change(_):
    with out:
        clear_output(wait=True)
        run_simulation(
            w_preset.value,
            w_Ks.value, w_psi.value,
            w_ths.value, w_thi.value,
            w_rainfall.value, w_duration.value
        )

for w in [w_preset, w_Ks, w_psi, w_ths, w_thi, w_rainfall, w_duration]:
    w.observe(on_change, names='value')

display(widgets.VBox([
    widgets.HTML("<h3 style='margin:0 0 8px;font-weight:500'>Green-Ampt infiltration simulator</h3>"),
    w_preset, w_Ks, w_psi, w_ths, w_thi, w_rainfall, w_duration,
    out
]))

on_change(None)   # draw initial plot
from ipywidgets import interact, FloatSlider

def update_soil_analysis(ec_value, na_value, cec_value):
    # Calculations
    if cec_value > 0:
        esp_val = (na_value / cec_value) * 100
    else:
        esp_val = 0.0

    # Soil Classification Logic
    if ec_value > 4 and esp_val < 15:
        soil_class = "Saline "
    elif ec_value < 4 and esp_val > 15:
        soil_class = "Sodic "
    elif ec_value > 4 and esp_val > 15:
        soil_class = "Saline-Sodic "
    else:
        soil_class = "Normal "

    # Output Display
    print("-" * 40)
    print(f"{'Soil Chemical Analysis':^40}")
    print("-" * 40)
    print(f"{'Soil Class:':<25} {soil_class:>15}")
    print(f"{'ESP (%):':<25} {esp_val:>12.2f}%")
    print(f"{'EC (dS/m):':<25} {ec_value:>13}")
    print("-" * 40)

# Interactive Widgets
interact(update_soil_analysis,
         ec_value=FloatSlider(min=0.1, max=15.0, step=0.1, value=5.2, description='EC (dS/m):'),
         na_value=FloatSlider(min=1.0, max=60.0, step=0.5, value=18.0, description='Na (meq/100g):'),
         cec_value=FloatSlider(min=10.0, max=120.0, step=1.0, value=25.0, description='CEC:'))
import matplotlib.pyplot as plt
import numpy as np

# %matplotlib inline

def draw_textured_triangle(sand, clay):
    silt = 100 - (sand + clay)

    if clay >= 40: res = "Clay"
    elif clay >= 27: res = "Clay Loam"
    elif sand >= 70: res = "Sandy"
    else: res = "Loam"

    fig, ax = plt.subplots(figsize=(8, 7))

    ticks = np.arange(0, 110, 10)
    for t in ticks:
        # (Sand gridlines - diagonal towards silt)
        ax.plot([t, t/2], [0, t*np.sin(np.pi/3)], color='gray', linestyle='--', linewidth=0.5)
        # (Clay gridlines - horizontal)
        ax.plot([t/2, 100-t/2], [t*np.sin(np.pi/3), t*np.sin(np.pi/3)], color='gray', linestyle='--', linewidth=0.5)
        # (Silt gridlines - diagonal towards sand)
        ax.plot([t, 50+t/2], [0, (100-t)*np.sin(np.pi/3)], color='gray', linestyle='--', linewidth=0.5)

        if t > 0 and t < 100:
            ax.text(t, -4, str(100-t), ha='center', fontsize=8, color='blue')
            ax.text(t/2 - 2, t*np.sin(np.pi/3), str(t), va='center', ha='right', fontsize=8, color='red')
            ax.text(100-t/2 + 2, t*np.sin(np.pi/3), str(100-t), va='center', ha='left', fontsize=8, color='green')

    points = np.array([[0, 0], [100, 0], [50, 86.6], [0, 0]])
    ax.plot(points[:, 0], points[:, 1], color='black', lw=2)

    # x = silt + 0.5 * clay
    px = (100 - sand) - (clay / 2)
    py = clay * 0.866

    ax.scatter(px, py, color='red', s=250, zorder=10, edgecolors='black')
    ax.text(px, py + 5, f"{res}\n(Sa:{sand}%, Cl:{clay}%)",
            color='red', fontweight='bold', ha='center', zorder=11, fontsize=12)

    ax.text(-15, -7, 'SAND 100%', fontsize=12, fontweight='bold', color='blue')
    ax.text(85, -7, 'SILT 100%', fontsize=12, fontweight='bold', color='green')
    ax.text(45, 95, 'CLAY 100%', fontsize=12, fontweight='bold', color='red')

    ax.set_title("Soil Texture Result with Grid", fontsize=16, pad=20)
    ax.axis('off')
    ax.set_xlim(-20, 120)
    ax.set_ylim(-15, 110)

    plt.show()

draw_textured_triangle(sand=60, clay=15)
